[package]
name = "posthog-wasm"
version = "0.1.0"
edition = "2021"
description = "A WebAssembly library for PostHog"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"

[profile.release]
opt-level = "s"
lto = true
